### ISSUE TITLE
delete text not working

### ISSUE THREAD

**Issue by erikwachters** [faeibson/lovelace-multiline-text-input-card#1]
Hi,

When I press the "delete" button nothing happens and I have this in my log:

> ERROR (MainThread) [frontend.js.latest.202002205] xx/community_plugin/lovelace-multiline-text-input-card/lovelace-multiline-text-input-card.js:134:4 Uncaught ReferenceError: setText is not defined

(replaced my HASS link with "xx")

Erik

**Comment by faeibson** [comment]
Ouch! Thank you.

**Comment by erikwachters** [comment]
Still the same problem.....
(Thanks for the quick action)

**Comment by faeibson** [comment]
Sorry, you're faster than me getting the repo straight :) fixed 1.0.2 now available.

**Comment by erikwachters** [comment]
LOL... sorry ;)
