### ISSUE TITLE
How to reorder icons?

### ISSUE THREAD

**Issue by kebel87** [faeibson/lovelace-multiline-text-input-card#2]
Hi,

Not an issue, but I wonder how to reorder icons so the save (send in my use case) is on the right, and delete/clear is on the left.

Thanks for this awesome card btw!

**Comment by faeibson** [comment]
Hi,

thank you for the request, I think that's really a thing worth implementing! Have not been thinking about this yet. I'm also planning to implement some kind of feedback after the state has been saved - I'm not quite sure at the moment, when I'll have time for doing so, but when, I will definitely add reorderable icons, too. If you have any other enhancements in mind, please just let me know :)

**Comment by kebel87** [comment]
Another idea I had is to add the ability to use standard messages that would be selectable from a dropdown list. So we’d have a very effective “message launchpad” card.

In my use case, I’m using the field to send critical notifications to my wife iPhone when she fail to hear regular sms.

**Comment by faeibson** [comment]
Hi again,

I finally managed to implement the reordering. Sorry for the waiting.
I will think about the dropdown list. Maybe this should be another card, but I like the idea. I created an issue for that.
