### ISSUE TITLE
var with more than 255 characters

### ISSUE THREAD

**Issue by nohumaninput** [faeibson/lovelace-multiline-text-input-card#8]
Hi,
I very much like your custom component.
Could you maybe give an example on how to use with snarky-snarks var component to use more than 255 characters?
I managed to configure both but still got an error about the limit of 255.
Thank you very much.

**Comment by faeibson** [comment]
Hi,
apparently the max length is limited by Home Assistant and therefore even var cannot provide a length of more than 255 characters. I believe it was different when I wrote the card but that was 3 years ago. Hence, unfortunately I will not be able to help you in this case, sorry.
https://github.com/snarky-snark/home-assistant-variables/issues/60

**Comment by faeibson** [comment]
@nohumaninput The card is capable of storing to var's attributes now, which allows up to 65535 characters each. Check it out.

**Comment by nohumaninput** [comment]
@faeibson This is wonderful! I already implemented and it works fine. Thank you very much!

**Comment by faeibson** [comment]
Thanks for the great feedback! Let me know if you have any other issues / suggestions to improve further.
